repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace

  # - repo: local
  #   hooks:
  #     - id: version-inc
  #       name: Version Increase
  #       entry: ./auto_version_bump.sh
  #       language: script
  #       files: .*
